name: LittleNebo
version: "1.1.0"
main: moe.reno.littlenebo.LittleNebo
api-version: 1.19
author: cutelilreno
description: A lightweight chat plugin with legacy, MiniMessage and PlaceholderAPI support.
website: https://github.com/cutelilreno/LittleNebo
softdepend: [PlaceholderAPI]
commands:
  littlenebo:
    description: Little Nebo main command
    usage: /littlenebo <reload|debug>
    aliases: [nebo]
    permission: littlenebo.admin
permissions:
  littlenebo.admin:
    description: Allows administration of Little Nebo
    default: op
  littlenebo.reload:
    description: Allows reloading Little Nebo conf
    default: op