name: LittleNebo
version: 1.0.0
main: moe.reno.littlenebo.LittleNebo
api-version: 1.21
author: cutelilreno
description: A simple chat plugin with MiniMessage support
website: https://reno.moe
depend: [PlaceholderAPI]
commands:
  littlenebo:
    description: Little Nebo main command
    usage: /littlenebo <reload|debug>
    aliases: [nebo]
    permission: littlenebo.admin
permissions:
  littlenebo.admin:
    description: Allows administration of Little Nebo
    default: op